# Generated by Django 5.2.16 on 2026-07-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MARKETING', 'Marketing Employee'), ('SALES_REP', 'Sales Representative'), ('SALES_MANAGER', 'Sales Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('SOFTWARE_ENGINEER', 'Software Engineer'), ('DIRECTOR', 'Director')], default='SALES_REP', max_length=30),
        ),
    ]
