# Generated by Django 5.2.16 on 2026-08-23 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_lead_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='REQUESTED', max_length=20)),
                ('technical_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'profile__role': 'TECH_LEAD'}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_technical_assessments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technical_assessments', to='crm.lead')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_technical_assessments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_technical_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalAssessmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='technical_assessments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.technicalassessment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_technical_assessment_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalAssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REQUESTED', 'Requested'), ('STARTED', 'Started'), ('UPDATED', 'Updated'), ('RECOMMENDATION_ADDED', 'Recommendation Added'), ('RECOMMENDATION_REMOVED', 'Recommendation Removed'), ('DOCUMENT_ADDED', 'Document Added'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], max_length=40)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.technicalassessment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technical_assessment_history_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalAssessmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited Availability'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20)),
                ('recommendation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='crm.technicalassessment')),
                ('engineer', models.ForeignKey(limit_choices_to={'profile__role': 'SOFTWARE_ENGINEER'}, on_delete=django.db.models.deletion.PROTECT, related_name='technical_assessment_recommendations', to=settings.AUTH_USER_MODEL)),
                ('recommended_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_technical_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='technicalassessment',
            index=models.Index(fields=['status'], name='tech_assess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='technicalassessment',
            index=models.Index(fields=['assigned_to', 'status'], name='tech_assess_owner_idx'),
        ),
        migrations.AddConstraint(
            model_name='technicalassessmentrecommendation',
            constraint=models.UniqueConstraint(fields=('assessment', 'engineer'), name='unique_engineer_per_technical_assessment'),
        ),
    ]
