# Generated by Django 5.2.16 on 2026-08-23 19:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_technicalassessment_technicalassessmentdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], default='REQUESTED', max_length=20)),
                ('financial_comments', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(limit_choices_to={'profile__role': 'FINANCIAL_OFFICER'}, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_financial_assessments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_assessments', to='crm.lead')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_financial_assessments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_financial_assessments', to=settings.AUTH_USER_MODEL)),
                ('technical_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financial_assessments', to='crm.technicalassessment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAssessmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='financial_assessments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.financialassessment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_financial_assessment_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAssessmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REQUESTED', 'Requested'), ('STARTED', 'Started'), ('UPDATED', 'Updated'), ('DOCUMENT_ADDED', 'Document Added'), ('SUBMITTED', 'Submitted'), ('REVIEWED', 'Reviewed')], max_length=40)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='crm.financialassessment')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_assessment_history_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='financialassessment',
            index=models.Index(fields=['status'], name='fin_assess_status_idx'),
        ),
        migrations.AddIndex(
            model_name='financialassessment',
            index=models.Index(fields=['assigned_to', 'status'], name='fin_assess_owner_idx'),
        ),
    ]
