# Generated by Django 5.2.16 on 2026-08-24 05:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_financialassessment_financialassessmentdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadOpportunityDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('decision_notes', models.TextField()),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_opportunity_decisions', to=settings.AUTH_USER_MODEL)),
                ('financial_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_decisions', to='crm.financialassessment')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_decision', to='crm.lead')),
                ('technical_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunity_decisions', to='crm.technicalassessment')),
            ],
            options={
                'ordering': ['-decided_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('source_lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='crm.lead')),
                ('opportunity_decision', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='deal', to='crm.leadopportunitydecision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
