# Generated by Django 5.2.16 on 2026-08-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_lead_requirement'),
        ('crm', '0010_notification_responsible_manager'),
    ]

    operations = [
    ]
