from django.urls import path

from .authentication import (
    CookieAwareTokenRefreshView,
    MFASetupConfirmView,
    MFASetupStartView,
    MFAVerifyView,
    ThrottledTokenObtainPairView,
)
from .views import (
    AdminDashboardSummaryView,
    AdminUserCreateView,
    AdminUserDeleteView,
    AdminUserDetailView,
    AdminUserListView,
    AdminUserPasswordResetEmailView,
    AdminUserUpdateView,
    CurrentUserProfileUpdateView,
    CurrentUserView,
    ForgotPasswordView,
    LogoutView,
    ProfileAvatarView,
    ResetPasswordView,
    SalesRepLookupView,
)


urlpatterns = [
    path(
        "login/",
        ThrottledTokenObtainPairView.as_view(),
        name="login",
    ),
    path(
        "mfa/setup/",
        MFASetupStartView.as_view(),
        name="mfa-setup-start",
    ),
    path(
        "mfa/setup/confirm/",
        MFASetupConfirmView.as_view(),
        name="mfa-setup-confirm",
    ),
    path(
        "mfa/verify/",
        MFAVerifyView.as_view(),
        name="mfa-verify",
    ),
    path(
        "refresh/",
        CookieAwareTokenRefreshView.as_view(),
        name="refresh",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
    path(
        "me/",
        CurrentUserView.as_view(),
        name="current-user",
    ),
    path(
        "me/profile/",
        CurrentUserProfileUpdateView.as_view(),
        name="current-user-profile",
    ),
    path(
        "profile-avatar/<str:token>/",
        ProfileAvatarView.as_view(),
        name="profile-avatar",
    ),
    path(
        "sales-representatives/",
        SalesRepLookupView.as_view(),
        name="sales-representative-list",
    ),
    path(
        "forgot-password/",
        ForgotPasswordView.as_view(),
        name="forgot-password",
    ),
    path(
        "reset-password/",
        ResetPasswordView.as_view(),
        name="reset-password",
    ),
    path(
        "admin/dashboard-summary/",
        AdminDashboardSummaryView.as_view(),
        name="admin-dashboard-summary",
    ),
    path(
        "admin/users/",
        AdminUserListView.as_view(),
        name="admin-user-list",
    ),
    path(
        "admin/users/create/",
        AdminUserCreateView.as_view(),
        name="admin-user-create",
    ),
    path(
        "admin/users/<int:pk>/update/",
        AdminUserUpdateView.as_view(),
        name="admin-user-update",
    ),
    path(
        "admin/users/<int:pk>/delete/",
        AdminUserDeleteView.as_view(),
        name="admin-user-delete",
    ),
    path(
        "admin/users/<int:pk>/password-reset-email/",
        AdminUserPasswordResetEmailView.as_view(),
        name="admin-user-password-reset-email",
    ),
    path(
        "admin/users/<int:pk>/",
        AdminUserDetailView.as_view(),
        name="admin-user-detail",
    ),
]
