import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react'
import { Alert, Box, Button, Chip, CircularProgress, Grid, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Typography } from '@mui/material'
import { AccessTimeRounded, AssignmentOutlined, AutorenewRounded, GroupsOutlined, HandshakeOutlined, RefreshRounded, TrendingUpRounded } from '@mui/icons-material'
import { useNavigate, useSearchParams } from 'react-router'
import AnalyticsFilterBar from '../components/analytics/AnalyticsFilterBar'
import { EmptyState, MetricCard, Section, SourceBars, TrendChart } from '../components/analytics/AnalyticsWidgets'
import { filtersToQuery, getExecutiveDashboard, getManagerDashboard, toLocalISODate, type AnalyticsFilters, type DashboardData } from '../services/analytics'

const primaryManager = ['leads_created','active_leads','deals_generated','lead_to_deal_conversion_rate','pending_assessments','overdue_follow_ups']
const primaryExecutive = ['active_leads','proceed','open_deals','won_deals','lost_deals','lead_to_deal_conversion_rate']
const labels: Record<string, string> = { leads_created: 'Leads Created', active_leads: 'Active Leads', deals_generated: 'Deals Generated', open_deals: 'Open Deals', won_deals: 'Won Deals', lost_deals: 'Lost Deals', lead_to_deal_conversion_rate: 'Lead → Deal Conversion', lead_to_proceed_rate: 'Lead → Proceed', pending_assessments: 'Pending Assessments', overdue_follow_ups: 'Overdue Follow-ups', proceed: 'Qualified / Proceed', do_not_proceed: 'Do Not Proceed', pending_final_decision: 'Pending Final Decision', financially_viable: 'Financially Viable', not_financially_viable: 'Not Financially Viable', commercial_reviews_required: 'Commercial Reviews Required', pending_commercial_exceptions: 'Pending Exceptions' }
const reportFor: Record<string, string> = { leads_created: 'lead-sources', active_leads: 'lead-status', deals_generated: 'deals', lead_to_deal_conversion_rate: 'lead-conversion', lead_to_proceed_rate: 'lead-conversion', pending_assessments: 'lead-status', overdue_follow_ups: 'sales-rep-performance' }
const iconFor: Record<string, ReactNode> = { leads_created: <GroupsOutlined />, active_leads: <AutorenewRounded />, deals_generated: <HandshakeOutlined />, lead_to_deal_conversion_rate: <TrendingUpRounded />, pending_assessments: <AssignmentOutlined />, overdue_follow_ups: <AccessTimeRounded /> }
const toneFor: Record<string, 'primary' | 'success' | 'warning' | 'error'> = { deals_generated: 'success', lead_to_deal_conversion_rate: 'success', pending_assessments: 'warning', overdue_follow_ups: 'error' }
const pipelineOrder = [['leads_created','Leads Created'],['finance_requested','Finance Requested'],['financially_suitable','Financially Suitable'],['technical_assessment','Technical Assessment'],['decision_ready','Decision Ready'],['proceed','Proceed'],['deal_created','Deal Created']] as const
const reportLinks = [['lead-sources','Lead Sources'],['lead-conversion','Lead Conversion'],['lead-status','Assessment Status'],['sales-rep-performance','Sales Rep Performance'],['deals','Deals']] as const

const defaultFilters = (): AnalyticsFilters => { const today = new Date(); return { date_from: toLocalISODate(new Date(today.getFullYear(), today.getMonth(), 1)), date_to: toLocalISODate(today) } }

export default function AnalyticsDashboardPage({ executive = false }: { executive?: boolean }) {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const [data, setData] = useState<DashboardData | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [updatedAt, setUpdatedAt] = useState<Date | null>(null)
  const queryKey = params.toString()
  const filters: AnalyticsFilters = useMemo(() => ({ ...defaultFilters(), ...Object.fromEntries(new URLSearchParams(queryKey).entries()) }), [queryKey])
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await (executive ? getExecutiveDashboard(filters) : getManagerDashboard(filters))); setUpdatedAt(new Date()) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Analytics could not be loaded.') } finally { setLoading(false) } }, [executive, filters])
  // Loading on route/filter changes is the external synchronization performed here.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load() }, [load])
  const openReport = (name: string, extra: Record<string,string> = {}) => navigate(`/reports/${name}?${filtersToQuery({ ...filters, ...extra })}`)
  const primary = executive ? primaryExecutive : primaryManager

  return <Box sx={{ maxWidth: 1540, mx: 'auto', px: { xs: 1.5, sm: 3 }, py: 2.5 }}>
    <Stack direction={{ xs: 'column', sm: 'row' }} sx={{ justifyContent: 'space-between', gap: 2, mb: 2 }}><Box><Typography variant="h4">{executive ? 'Business Development Overview' : 'Sales Operations'}</Typography><Typography color="text.secondary" sx={{ mt: .25 }}>{executive ? 'Strategic performance, acquisition effectiveness and opportunity outcomes.' : 'Monitor pipeline health, team activity and opportunities requiring attention.'}</Typography></Box><Stack direction="row" spacing={1} sx={{ alignItems: 'center' }}>{updatedAt && <Typography color="text.secondary" sx={{ fontSize: 11.5 }}>Last updated: {updatedAt.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</Typography>}<Button variant="outlined" startIcon={<RefreshRounded />} onClick={() => void load()}>Refresh</Button></Stack></Stack>
    <AnalyticsFilterBar key={params.toString()} value={filters} options={data?.filter_options} onApply={(next) => setParams(filtersToQuery(next))} />
    {error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
    {loading ? <Stack sx={{ alignItems: 'center', py: 10 }}><CircularProgress /></Stack> : data && <Stack spacing={2} sx={{ mt: 2 }}>
      <Grid container spacing={1.5}>{primary.map((key) => <Grid key={key} size={{ xs: 12, sm: 6, md: executive ? 3 : 4, xl: executive ? 3 : 2 }}><MetricCard label={labels[key]} value={key.endsWith('_rate') ? `${data.kpis[key] ?? 0}%` : Math.trunc(data.kpis[key] ?? 0)} tooltip={data.metric_definitions[key] || labels[key]} icon={iconFor[key] || <TrendingUpRounded />} tone={toneFor[key]} onClick={() => openReport(reportFor[key] || 'lead-status')} /></Grid>)}</Grid>
      {!executive && data.assessment_pipeline && <Section title="Lead Assessment Pipeline" subtitle="Progress from Lead creation through specialist assessment and Deal creation."><Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2,1fr)', lg: 'repeat(7,1fr)' }, gap: { xs: 1, lg: 0 } }}>{pipelineOrder.map(([key,label],index) => { const value = data.assessment_pipeline?.[key] || 0; const previous = index ? data.assessment_pipeline?.[pipelineOrder[index-1][0]] || 0 : 0; return <Box key={key} sx={{ position: 'relative', p: 1.5, textAlign: 'center', color: index < 2 ? 'white' : 'text.primary', bgcolor: index === 0 ? 'primary.dark' : index === 1 ? 'primary.main' : `rgba(11,92,255,${Math.max(.06,.2-index*.018)})`, clipPath: { lg: index === 0 ? 'polygon(0 0,92% 0,100% 50%,92% 100%,0 100%)' : index === 6 ? 'polygon(0 0,100% 0,92% 100%,0 100%,8% 50%)' : 'polygon(0 0,92% 0,100% 50%,92% 100%,0 100%,8% 50%)' } }}><Typography sx={{ fontSize: 10.5, fontWeight: 650 }}>{label}</Typography><Typography variant="h5" sx={{ fontWeight: 800 }}>{value}</Typography>{index > 0 && <Typography sx={{ fontSize: 9, opacity: .75 }}>{previous ? `${Math.round(value/previous*100)}% of prior` : '—'}</Typography>}</Box> })}</Box></Section>}
      <Grid container spacing={2}><Grid size={{ xs: 12, lg: 7 }}><Section title={executive ? 'Business Trend' : 'Leads & Deals Trend'} subtitle="Real activity grouped for the selected reporting period."><TrendChart rows={(executive ? data.business_trend : data.trend) || []} executive={executive} /></Section></Grid><Grid size={{ xs: 12, lg: 5 }}><Section title={executive ? 'Business Source Contribution' : 'Lead Source Performance'} subtitle="Compare acquisition volume, Deal output and conversion."><SourceBars rows={data.source_performance} onSelect={(source) => openReport('lead-sources', { source })} /></Section></Grid></Grid>
      {executive && data.pipeline_summary && <Section title="Pipeline Health" subtitle="Current progression across the assessment and decision pipeline."><Box sx={{ display: 'grid', gridTemplateColumns: { xs: 'repeat(2,1fr)', md: 'repeat(4,1fr)', xl: 'repeat(7,1fr)' }, gap: 1 }}>{pipelineOrder.map(([key,label]) => <Box key={key} onClick={() => openReport('lead-status')} sx={{ p: 1.5, bgcolor: 'action.hover', borderRadius: 1.5, cursor: 'pointer' }}><Typography color="text.secondary" sx={{ fontSize: 11 }}>{label}</Typography><Typography variant="h5" sx={{ mt: .25, fontWeight: 750 }}>{data.pipeline_summary?.[key] || 0}</Typography></Box>)}</Box></Section>}
      {executive && data.commercial_health && <Section title="Commercial Health" subtitle="Financial viability and exception approval remain separate evidence streams."><Grid container spacing={1.5}>{Object.entries(data.commercial_health).map(([key,value]) => <Grid key={key} size={{ xs: 12, sm: 6, lg: 3 }}><Box onClick={() => key === 'pending_commercial_exceptions' && navigate('/executive/approvals')} sx={{ p: 2, bgcolor: 'action.hover', borderRadius: 2, cursor: key === 'pending_commercial_exceptions' ? 'pointer' : 'default' }}><Typography color="text.secondary" sx={{ fontSize: 12 }}>{labels[key] || key.replaceAll('_',' ')}</Typography><Typography variant="h4" sx={{ fontWeight: 750 }}>{value}</Typography></Box></Grid>)}</Grid></Section>}
      {executive && data.decision_outcomes && <Section title="Opportunity Decision Outcomes" subtitle="Pending Leads are excluded from the Proceed Rate denominator."><Grid container spacing={1.5}>{Object.entries(data.decision_outcomes).map(([key,value]) => <Grid key={key} size={{ xs: 12, sm: 4 }}><Box sx={{ p: 2, bgcolor: 'action.hover', borderRadius: 2 }}><Typography color="text.secondary" sx={{ fontSize: 12 }}>{labels[key === 'pending' ? 'pending_final_decision' : key] || key.replaceAll('_',' ')}</Typography><Typography variant="h4" sx={{ fontWeight: 750 }}>{value}</Typography></Box></Grid>)}</Grid></Section>}
      {executive && <Grid container spacing={2}><Grid size={{ xs: 12, xl: 7 }}><Section title="Sales Representative Performance" subtitle="Factual organisation-wide activity and conversion outcomes."><TableContainer><Table size="small"><TableHead><TableRow>{['Sales Representative','Assigned Leads','Proceed','Deals','Conversion','Completed Follow-ups','Overdue'].map((heading) => <TableCell key={heading} sx={{ bgcolor: 'action.hover', fontWeight: 700, fontSize: 11 }}>{heading}</TableCell>)}</TableRow></TableHead><TableBody>{data.sales_rep_summary?.map((row) => <TableRow hover key={String(row.sales_rep)} onClick={() => openReport('sales-rep-performance', { sales_rep: String(row.sales_rep) })} sx={{ cursor: 'pointer' }}>{['sales_rep_name','assigned_leads','proceed','deals','conversion_rate','follow_ups_completed','overdue_follow_ups'].map((key) => <TableCell key={key} sx={{ fontSize: 12 }}>{String(row[key] ?? '—')}{key === 'conversion_rate' ? '%' : ''}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer></Section></Grid><Grid size={{ xs: 12, xl: 5 }}><Section title="Management Attention" subtitle="Oversight indicators; operational actions remain with Sales Management." accent="warning">{data.attention_required?.length ? <Stack spacing={.5}>{data.attention_required.map((item) => <Stack key={`${item.lead_id}-${item.issue}`} direction="row" onClick={() => navigate(`/leads/${item.lead_id}`)} sx={{ alignItems: 'center', gap: 1, p: 1.1, borderBottom: '1px solid', borderColor: 'divider', cursor: 'pointer', '&:hover': { bgcolor: 'action.hover' } }}><Box sx={{ flex: 1, minWidth: 0 }}><Typography sx={{ fontWeight: 650, fontSize: 12.5 }}>{item.lead}</Typography><Typography color="warning.main" sx={{ fontSize: 11.5 }}>{item.issue}</Typography></Box><Chip size="small" label={`${item.waiting_days} day${item.waiting_days === 1 ? '' : 's'}`} /><Typography color="primary.main" sx={{ fontSize: 11.5, fontWeight: 650 }}>View →</Typography></Stack>)}</Stack> : <EmptyState text="No management attention items for this period." />}</Section></Grid></Grid>}
      {!executive && <Grid container spacing={2}><Grid size={{ xs: 12, xl: 7 }}><Section title="Team Performance" subtitle="Factual activity and outcomes for Leads in this cohort."><TableContainer><Table size="small"><TableHead><TableRow>{['Sales Rep','Assigned Leads','Communications','Completed Follow-ups','Overdue','Proceed','Deals','Conversion'].map((heading) => <TableCell key={heading} sx={{ bgcolor: 'action.hover', fontWeight: 700, fontSize: 11 }}>{heading}</TableCell>)}</TableRow></TableHead><TableBody>{data.team_performance?.map((row) => <TableRow hover key={String(row.sales_rep)} onClick={() => openReport('sales-rep-performance', { sales_rep: String(row.sales_rep) })} sx={{ cursor: 'pointer' }}>{['sales_rep_name','assigned_leads','communications','follow_ups_completed','overdue_follow_ups','proceed','deals','conversion_rate'].map((key) => <TableCell key={key} sx={{ fontSize: 12 }}>{String(row[key] ?? '—')}{key === 'conversion_rate' ? '%' : ''}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer></Section></Grid><Grid size={{ xs: 12, xl: 5 }}><Section title="Attention Required" subtitle="Items requiring Sales Manager action." accent="warning">{data.attention_required?.length ? <Stack spacing={.75}>{data.attention_required.map((item) => <Stack key={`${item.lead_id}-${item.issue}`} direction="row" onClick={() => navigate(`/leads/${item.lead_id}`)} sx={{ alignItems: 'center', gap: 1, p: 1.15, borderBottom: '1px solid', borderColor: 'divider', cursor: 'pointer', '&:hover': { bgcolor: 'action.hover' } }}><Box sx={{ flex: 1, minWidth: 0 }}><Typography sx={{ fontWeight: 650, fontSize: 12.5 }}>{item.lead}</Typography><Typography color="warning.main" sx={{ fontSize: 11.5 }}>{item.issue}</Typography></Box><Chip size="small" color={item.waiting_days ? 'warning' : 'default'} label={`${item.waiting_days} day${item.waiting_days === 1 ? '' : 's'}`} /><Typography color="primary.main" sx={{ fontSize: 11.5, fontWeight: 650 }}>View Lead →</Typography></Stack>)}</Stack> : <EmptyState text="Nothing needs your attention right now." />}</Section></Grid></Grid>}
      <Section title="Reports" subtitle="Open the evidence behind dashboard results."><Grid container spacing={1.25}>{reportLinks.map(([name,label]) => <Grid key={name} size={{ xs: 12, sm: 6, lg: 2.4 }}><Button fullWidth variant="outlined" onClick={() => openReport(name)} sx={{ justifyContent: 'space-between', py: 1.4 }}>{label}<span>→</span></Button></Grid>)}</Grid></Section>
    </Stack>}
  </Box>
}
