import { useEffect, useMemo, useState } from 'react'
import { Alert, Box, Button, Chip, CircularProgress, Grid, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { AssignmentOutlined, DownloadRounded, PictureAsPdfOutlined, RefreshRounded } from '@mui/icons-material'
import { useNavigate, useParams, useSearchParams } from 'react-router'
import AnalyticsFilterBar from '../components/analytics/AnalyticsFilterBar'
import { EmptyState, MetricCard, Section, SourceBars } from '../components/analytics/AnalyticsWidgets'
import { downloadReport, downloadReportPdf, filtersToQuery, getReport, toLocalISODate, type AnalyticsFilters, type FilterOptions, type ReportData, type SourcePerformance } from '../services/analytics'
import { getCurrentUser, type CurrentUser } from '../services/auth'

const reportOptions = [['lead-sources','Lead Source Report'],['lead-conversion','Lead Conversion Report'],['lead-status','Lead Status & Assessment Report'],['sales-rep-performance','Sales Rep Performance Report'],['deals','Deal Pipeline Report']] as const
const reportDescriptions: Record<string, string> = {
  'lead-sources': 'Analyse Lead acquisition channels and conversion into Deals.',
  'lead-conversion': 'Analyse movement from Leads to Proceed decisions and generated Deals.',
  'lead-status': 'Monitor Lead assessment stages, final decisions and aging.',
  'sales-rep-performance': 'Compare Lead workload, engagement, follow-up activity and Deal conversion by Sales Representative.',
  deals: 'Monitor generated Deals and their current pipeline status.',
}
const columns: Record<string, Array<[string,string]>> = {
  'lead-sources': [['created_at','Created'],['lead','Lead'],['company','Company'],['source_display','Source'],['source_details','Source Details'],['sales_rep_name','Assigned Rep'],['status_display','Status'],['final_decision','Final Decision'],['deal','Deal']],
  'lead-conversion': [['lead','Lead'],['created_at','Created'],['source_display','Source'],['sales_rep_name','Sales Rep'],['finance_outcome','Finance Outcome'],['technical_state','Technical State'],['final_decision','Final Decision'],['deal','Deal'],['deal_created_at','Deal Created']],
  'lead-status': [['lead','Lead'],['company','Company'],['sales_rep_name','Assigned Rep'],['finance_state','Finance State'],['technical_state','Technical State'],['final_decision','Final Decision'],['assessment_stage','Current Assessment State'],['days_in_current_state','Days in State']],
  'sales-rep-performance': [['sales_rep_name','Sales Rep'],['assigned_leads','Assigned Leads'],['communications','Communications'],['follow_ups_completed','Completed Follow-ups'],['overdue_follow_ups','Overdue'],['proceed','Proceed'],['deals','Deals'],['conversion_rate','Conversion %']],
  deals: [['deal','Deal'],['lead','Originating Lead'],['company','Company'],['source_display','Lead Source'],['sales_rep_name','Sales Rep'],['deal_created_at','Created'],['deal_status','Status']],
}
const humanize = (value: string) => value.replaceAll('_',' ').toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase())
const display = (key: string, value: unknown) => { if (value === null || value === undefined || value === '') return '—'; if ((key.endsWith('_at') || key === 'created_at') && typeof value === 'string') return new Date(value).toLocaleDateString(); if (key === 'assessment_stage') return humanize(String(value)); return String(value) }
const defaults = (): AnalyticsFilters => { const now = new Date(); return { date_from: toLocalISODate(new Date(now.getFullYear(),now.getMonth(),1)), date_to: toLocalISODate(now) } }

function summaryMetrics(name: string, data: ReportData): Array<[string,string | number]> {
  void name
  return data.metrics.map((metric) => [metric.label, `${metric.value}${metric.suffix || ''}`])
}

function observations(name: string, data: ReportData): string[] {
  void name
  return data.observations
}

export default function ReportsPage() {
  const { reportName = 'lead-sources' } = useParams(); const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const initialQuery = params.toString(); const initial = useMemo(() => ({ ...defaults(), ...Object.fromEntries(new URLSearchParams(initialQuery).entries()) }), [initialQuery])
  const [draftReport,setDraftReport] = useState(reportName); const [draftFilters,setDraftFilters] = useState<AnalyticsFilters>(initial); const [appliedFilters,setAppliedFilters] = useState<AnalyticsFilters | null>(null); const [data,setData] = useState<ReportData | null>(null); const [options,setOptions] = useState<FilterOptions | undefined>(); const [user,setUser] = useState<CurrentUser | null>(null); const [generatedAt,setGeneratedAt] = useState<Date | null>(null); const [loading,setLoading] = useState(false); const [exporting,setExporting] = useState(false); const [exportingPdf,setExportingPdf] = useState(false); const [error,setError] = useState('')
  useEffect(() => { void getCurrentUser().then(setUser).catch(() => setUser(null)) }, [])
  useEffect(() => { void getReport(reportName, initial).then((result)=>setOptions(result.filter_options)).catch(()=>setOptions(undefined)) }, [initial, reportName])
  const generate = async (filters = draftFilters) => { if (!filters.date_from || !filters.date_to || filters.date_from > filters.date_to) { setError('Choose a valid reporting period.'); return } setLoading(true); setError(''); try { const result = await getReport(draftReport,filters); setData(result); setOptions(result.filter_options); setAppliedFilters(filters); setGeneratedAt(new Date()); setParams(filtersToQuery(filters)); if (draftReport !== reportName) navigate(`/reports/${draftReport}?${filtersToQuery(filters)}`, { replace: true }) } catch (caught) { setError(caught instanceof Error ? caught.message : 'The report could not be generated.') } finally { setLoading(false) } }
  const metrics = useMemo(() => data ? summaryMetrics(data.report,data) : [],[data]); const notes = data ? observations(data.report,data) : []
  const exportCsv = async () => { if (!data || !appliedFilters) return; setExporting(true); try { await downloadReport(data.report,appliedFilters) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Export failed.') } finally { setExporting(false) } }
  const exportPdf = async () => { if (!data || !appliedFilters || exportingPdf) return; setExportingPdf(true); setError(''); try { await downloadReportPdf(data.report,appliedFilters) } catch (caught) { setError(caught instanceof Error ? caught.message : 'PDF generation failed.') } finally { setExportingPdf(false) } }
  const sourceRows = data?.report === 'lead-sources' && Array.isArray(data.summary) ? data.summary as unknown as SourcePerformance[] : []
  const totalSourceLeads = sourceRows.reduce((sum,row)=>sum+row.leads,0)

  return <Box sx={{ maxWidth: 1540, mx: 'auto', px: { xs: 1.5, sm: 3 }, py: 2.5 }}>
    <Box className="analytics-screen-header"><Typography variant="h4">Reports & Analytics</Typography><Typography color="text.secondary">Configure, analyse and export CRM performance reports.</Typography></Box>
    <Typography color="text.secondary" sx={{ mt:.5,fontSize:12.5 }}>{reportDescriptions[draftReport]}</Typography>
    <Paper className="report-builder" variant="outlined" sx={{ p: 2, mt: 2, borderColor: 'var(--eleven-border)', boxShadow: 'var(--eleven-shadow)' }}><Typography variant="h6" sx={{ fontSize: 16 }}>Report Builder</Typography><Typography color="text.secondary" sx={{ fontSize: 12.5, mb: 1.5 }}>Configure report parameters, then generate the analysis.</Typography><TextField select size="small" label="Report Type" value={draftReport} onChange={(event)=>setDraftReport(event.target.value)} sx={{ minWidth: { xs: '100%', sm: 280 }, mb: 1.5 }}>{reportOptions.map(([value,label])=><MenuItem key={value} value={value}>{label}</MenuItem>)}</TextField><AnalyticsFilterBar value={draftFilters} options={options} showDealStatus={draftReport==='deals'} showActions={false} onApply={setDraftFilters} /><Stack direction="row" spacing={1} sx={{ justifyContent: 'flex-end', mt: 1.5 }}><Button onClick={()=>{ const next=defaults(); setDraftFilters(next); setData(null); setError('') }}>Reset</Button><Button variant="contained" onClick={()=>void generate()}>Generate Report</Button></Stack></Paper>
    {error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}
    {loading && <Paper variant="outlined" sx={{ mt: 2, py: 9 }}><Stack sx={{ alignItems: 'center' }} spacing={1}><CircularProgress /><Typography color="text.secondary">Generating report…</Typography></Stack></Paper>}
    {!loading && !data && <Paper variant="outlined" sx={{ mt: 2 }}><EmptyState text="Configure the report above, then select Generate Report." /></Paper>}
    {!loading && data && appliedFilters && <Box className="generated-report" sx={{ mt: 2 }}>
      <Paper variant="outlined" sx={{ p: 2, borderColor: 'var(--eleven-border)' }}><Stack direction={{ xs:'column',md:'row' }} sx={{ justifyContent:'space-between',gap:2 }}><Box><Typography variant="h5">{data.title}</Typography><Stack direction="row" useFlexGap sx={{ flexWrap:'wrap',gap:.75,mt:.5 }}><Typography color="text.secondary" sx={{ fontSize:11.5 }}>Reporting period: {appliedFilters.date_from} – {appliedFilters.date_to}</Typography><Typography color="text.disabled">•</Typography><Typography color="text.secondary" sx={{ fontSize:11.5 }}>Generated: {generatedAt?.toLocaleString()}</Typography><Typography color="text.disabled">•</Typography><Typography color="text.secondary" sx={{ fontSize:11.5 }}>Generated by: {user ? `${user.first_name || user.username} (${user.role_display})` : 'Authenticated user'}</Typography></Stack><Stack direction="row" useFlexGap sx={{ flexWrap:'wrap',gap:.5,mt:1 }}>{Object.entries(appliedFilters).filter(([,value])=>value).map(([key,value])=><Chip key={key} size="small" variant="outlined" label={`${humanize(key)}: ${key.startsWith('date_') ? value : humanize(String(value))}`} />)}</Stack></Box><Stack className="report-actions" direction="row" spacing={1}><Button variant="outlined" startIcon={<RefreshRounded />} onClick={()=>void generate(appliedFilters)}>Refresh</Button><Button variant="outlined" startIcon={<PictureAsPdfOutlined />} disabled={exportingPdf} onClick={()=>void exportPdf()}>{exportingPdf?'Generating PDF…':'Export PDF'}</Button><Button variant="outlined" startIcon={<DownloadRounded />} disabled={exporting} onClick={()=>void exportCsv()}>{exporting?'Exporting…':'Export CSV'}</Button></Stack></Stack></Paper>
      {!data.records.length ? <Paper variant="outlined" sx={{ mt:2 }}><EmptyState text="No records matched the selected report criteria." /></Paper> : <Stack spacing={2} sx={{ mt:2 }}>
        <Grid container spacing={1.25}>{metrics.map(([label,value],index)=><Grid key={label} size={{ xs:12,sm:6,md:4,xl: metrics.length>4?2.4:3 }}><MetricCard label={label} value={value} tooltip={`${label} for the selected report filters.`} tone={index===2?'success':'primary'} /></Grid>)}</Grid>
        {data.report==='lead-sources' && <Grid container spacing={2}><Grid size={{ xs:12,lg:6 }}><Section title="Best Source Performance" subtitle="Leads and Deals by acquisition source."><SourceBars rows={sourceRows} /></Section></Grid><Grid size={{ xs:12,lg:6 }}><Section title="Source Performance Table" subtitle="Cohort contribution and conversion."><TableContainer><Table size="small"><TableHead><TableRow>{['Source','Leads','% of Leads','Proceed','Deals','Conversion'].map((h)=><TableCell key={h} sx={{ fontWeight:700,bgcolor:'action.hover' }}>{h}</TableCell>)}</TableRow></TableHead><TableBody>{sourceRows.map((row)=><TableRow key={row.source}><TableCell>{row.source_display}</TableCell><TableCell>{row.leads}</TableCell><TableCell>{totalSourceLeads?`${Math.round(row.leads/totalSourceLeads*1000)/10}%`:'0%'}</TableCell><TableCell>{row.proceed}</TableCell><TableCell>{row.deals}</TableCell><TableCell>{row.conversion_rate}%</TableCell></TableRow>)}</TableBody></Table></TableContainer></Section></Grid></Grid>}
        {data.report==='lead-conversion' && <><Section title="Lead Conversion Flow" subtitle="Lead cohort progression from creation to Proceed decisions and generated Deals."><Stack direction={{ xs:'column',sm:'row' }} spacing={1}>{metrics.slice(0,3).map(([label,value],index)=><Box key={label} sx={{ flex:1,p:2,textAlign:'center',bgcolor:index===0?'primary.main':'var(--eleven-primary-soft)',color:index===0?'white':'text.primary',borderRadius:1.5 }}><Typography sx={{ fontSize:11 }}>{label}</Typography><Typography variant="h5">{value}</Typography></Box>)}</Stack></Section><Section title="Conversion Rates" subtitle="Each rate states its funnel denominator explicitly."><Grid container spacing={1}>{metrics.slice(3).map(([label,value])=><Grid key={label} size={{ xs:12,sm:4 }}><Stack direction="row" sx={{ justifyContent:'space-between',p:1.25,bgcolor:'action.hover',borderRadius:1 }}><Typography sx={{ fontSize:12.5 }}>{label}</Typography><Typography sx={{ fontWeight:750 }}>{value}</Typography></Stack></Grid>)}</Grid></Section></>}
        {data.report==='lead-status' && <><Section title="Current Assessment Stage Distribution" subtitle="The current workflow position of each Lead."><Grid container spacing={1}>{Object.entries(data.distributions.assessment_stages || {}).map(([key,value])=><Grid key={key} size={{ xs:12,sm:6,md:4 }}><Stack direction="row" sx={{ justifyContent:'space-between',p:1.25,bgcolor:'action.hover',borderRadius:1 }}><Typography sx={{ fontSize:12.5 }}>{humanize(key)}</Typography><Typography sx={{ fontWeight:750 }}>{value}</Typography></Stack></Grid>)}</Grid></Section><Section title="Final Decision Distribution" subtitle="Final decisions are counted independently from the current assessment stage."><Grid container spacing={1}>{Object.entries(data.distributions.final_decisions || {}).map(([key,value])=><Grid key={key} size={{ xs:12,sm:4 }}><Stack direction="row" sx={{ justifyContent:'space-between',p:1.25,bgcolor:'action.hover',borderRadius:1 }}><Typography sx={{ fontSize:12.5 }}>{humanize(key)}</Typography><Typography sx={{ fontWeight:750 }}>{value}</Typography></Stack></Grid>)}</Grid></Section><Section title="Lead Aging / Attention Required" subtitle={`Longest-running current states first; stale means more than ${data.stale_lead_days} days.`}><TableContainer sx={{ maxHeight:360 }}><Table stickyHeader size="small"><TableHead><TableRow>{['Lead','Current Assessment Stage','Assigned Rep','Days in Current State'].map((label)=><TableCell key={label} sx={{ fontWeight:700,bgcolor:'action.hover' }}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{data.aging_records.map((row,index)=><TableRow key={String(row.lead_id || index)}><TableCell>{display('lead',row.lead)}</TableCell><TableCell>{display('assessment_stage',row.assessment_stage)}</TableCell><TableCell>{display('sales_rep_name',row.sales_rep_name)}</TableCell><TableCell>{display('days_in_current_state',row.days_in_current_state)}</TableCell></TableRow>)}</TableBody></Table></TableContainer></Section></>}
        {notes.length>0 && <Alert severity="info" icon={<AssignmentOutlined />}><Typography sx={{ fontWeight:700,fontSize:13 }}>Key observations</Typography>{notes.map((note)=><Typography key={note} sx={{ fontSize:12.5 }}>• {note}</Typography>)}</Alert>}
        <Section title="Underlying Records" subtitle="Records used to calculate this report."><TableContainer sx={{ maxHeight:620 }}><Table stickyHeader size="small"><TableHead><TableRow>{columns[data.report].map(([key,label])=><TableCell key={key} sx={{ fontWeight:700,bgcolor:'action.hover',whiteSpace:'nowrap' }}>{label}</TableCell>)}</TableRow></TableHead><TableBody>{data.records.map((row,index)=><TableRow hover key={String(row.lead_id||row.sales_rep||index)} onClick={()=>{ if(row.lead_id) navigate(`/leads/${row.lead_id}`) }} sx={{ cursor:row.lead_id?'pointer':'default' }}>{columns[data.report].map(([key])=><TableCell key={key} sx={{ whiteSpace:'nowrap',fontSize:12 }}>{display(key,row[key])}</TableCell>)}</TableRow>)}</TableBody></Table></TableContainer></Section>
      </Stack>}
    </Box>}
  </Box>
}
